name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build --no-cache -t sidvish/crud-service:latest .

    - name: Validate Prisma Client Generation
      run: |
        docker run --rm sidvish/crud-service:latest ls -la /app/node_modules/.prisma

    - name: Push Docker image
      run: |
        docker push sidvish/crud-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job will only run after the build job completes

    steps:
    - name: SSH to EC2 and pull Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          # Pull the latest image from Docker Hub
          docker pull sidvish/crud-service:latest

          # Stop and remove the existing container (if any)
          container_name="crud-service-container"
          docker ps -q -f "name=$container_name" | grep -q . && docker stop $container_name && docker rm $container_name

          # Run the new container with the DATABASE_URL environment variable
          docker run -d -p 3000:3000 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --name $container_name sidvish/crud-service:latest

          # Optional: Clean up unused images (if any)
          docker image prune -f
